In [1]:
import numpy as np
import tensorflow as tf

In [4]:
_1d_tensor = np.array([1.3,1,4.0,23.99])

In [5]:
print(_1d_tensor)

[  1.3    1.     4.    23.99]


In [6]:
print(_1d_tensor[0])

1.3


In [8]:
print(_1d_tensor[2])

4.0


In [9]:
tf_tensor = tf.convert_to_tensor(_1d_tensor,dtype = tf.float32)

In [11]:
with tf.Session() as sess:
    print(sess.run(tf_tensor))
    print(sess.run(tf_tensor[0]))
    print(sess.run(tf_tensor[2]))

[  1.29999995   1.           4.          23.98999977]
1.3
4.0


In [14]:
_2d_tensor = np.array([(1,2,3,4),(4,5,6,7),(8,9,10,11),(12,13,14,15)])

In [15]:
print(_2d_tensor)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [17]:
print(_2d_tensor[0][3])

4


In [18]:
print(_2d_tensor[3][2])

14


In [29]:
print(_2d_tensor[0:2,0:2])

[[1 2]
 [4 5]]


In [32]:
tf_2d_tensor = tf.convert_to_tensor(_2d_tensor,dtype = tf.float32 , name = "x")

In [34]:
with tf.Session() as sess:
    print (sess.run(tf_2d_tensor))

[[  1.   2.   3.   4.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]]
